### ISSUE TITLE
User doesn't lose units 

### ISSUE THREAD

**Issue by linmar22** [shdwp/dcs_liberation#37]
Mission debrief screen doesn't show any losses on either player or enemy side.
The number of units/aircraft available for the next mission stays the same.

Nothing out of the ordinary on the setup - application running as admin, running on Python 3.6.0, as per documentation.

Same issue cannot be reproduced on a different machine - Python 3.6.5

**Comment by zbenesch** [comment]
You possibly did not load the debroef correctly, check faq.

**Comment by shdwp** [comment]
The list is usually empty when there's something wrong with the debriefing indeed.

I'd suppose there's couple of bugs in the 1.4 regarding the debrief, since I redo that part. 

If you encounter it again - could you please gather logs (you can access them in Configuration menu) and debrief file for me to look at?

**Comment by calvinmorrow** [comment]
Just played a few missions in 1.4.4 multiplayer and ran into the same issue:  No results are displayed after the mission.  Our A10 pilot actually got shot down and it wasn't recorded in the results screen and did not reflect in the base inventory either (base still showed a single A10).

Python logs and debrief.log: https://gist.github.com/calvinmorrow/fd25c42f3a4d5a97db1d26c232005885

**Comment by shdwp** [comment]
Fixed by @calvinmorrow.
