### ISSUE TITLE
prepare minor release (1.5.1)

### ISSUE THREAD

**Issue by wrycu** [shdwp/dcs_liberation#74]
@Khopa has a lot of changes staged; getting them to a stable version where everything WIP is done may take a while. In the mean time, I'll prepare a minor bump with the following features:
* F-14B INS alignment pre-stored (#73)
* F-16C support (#72)

Stretch goal:
* SEAD screen size (#67)
* Correct UH-1 frequency (#64)
* No air defenses spawn (#36)
* View time of day before selecting aircraft (#19)

**Comment by jayrook** [comment]
How do you use this? Sorry, I really am quite clueless when it comes to this sort of thing.

**Comment by jayrook** [comment]
Thanks!

**Comment by wrycu** [comment]
Okay, I'll try to get the build together tomorrow.

**Comment by Khopa** [comment]
I had a quick look, I get the following error when clicking proceed : 

> Traceback (most recent call last):
  File "D:\Software\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Users\Clement\Desktop\dcs_liberation-master\ui\eventmenu.py", line 226, in start
    self.game.initiate_event(self.event)
  File "C:\Users\Clement\Desktop\dcs_liberation-master\game\game.py", line 245, in initiate_event
    event.generate()
  File "C:\Users\Clement\Desktop\dcs_liberation-master\game\event\event.py", line 117, in generate
    self.operation.generate()
  File "C:\Users\Clement\Desktop\dcs_liberation-master\game\operation\frontlineattack.py", line 56, in generate
    self.airgen.generate_cas_strikegroup(*assigned_units_split(planes_flights), at=self.attackers_starting_position)
  File "C:\Users\Clement\Desktop\dcs_liberation-master\gen\aircraft.py", line 289, in generate_cas_strikegroup
    at=at and at or self._group_point(self.conflict.air_attackers_location))
  File "C:\Users\Clement\Desktop\dcs_liberation-master\gen\aircraft.py", line 212, in _generate_group
    return self._generate_inflight(name, side, unit_type, count, client_count, at.position)
  File "C:\Users\Clement\Desktop\dcs_liberation-master\gen\aircraft.py", line 173, in _generate_inflight
    group_size=count)
  File "D:\Software\Python37\lib\site-packages\dcs\mission.py", line 1153, in flight_group
    position, altitude, speed, maintask, group_size)
  File "D:\Software\Python37\lib\site-packages\dcs\mission.py", line 1004, in flight_group_inflight
    p = self.aircraft(name + " Pilot #{nr}".format(nr=i), aircraft_type, country)
  File "D:\Software\Python37\lib\site-packages\dcs\mission.py", line 841, in aircraft
    return Plane(self.next_unit_id(), self.string(name), _type, country)
  File "D:\Software\Python37\lib\site-packages\dcs\unit.py", line 218, in __init__
    super(Plane, self).__init__(_id, name, _type, _country)
  File "D:\Software\Python37\lib\site-packages\dcs\unit.py", line 76, in __init__
    self.livery_id = self.unit_type.default_livery(_country.name)
  File "D:\Software\Python37\lib\site-packages\dcs\unittype.py", line 163, in default_livery
    liveries = cls.Liveries
AttributeError: type object 'F_16C_50' has no attribute 'Liveries'

This is because the F16C has no Liveries, which cause a bug in pydcs when trying to use the aircraft. 
I imported manually one of my fix from qt_ui branch in master :

`
class DefaultLiveries:
    class Default(Enum):
        af_standard = ""

OH_58D.Liveries = DefaultLiveries
F_16C_50.Liveries = DefaultLiveries
P_51D_30_NA.Liveries = DefaultLiveries
`
 I added this at the beginning of db.py which prevent the issue from occuring for the aircraft type missing liveries options, this is just injecting a blank field for liveries (and it doesn't cause issues in DCS).

**Comment by wrycu** [comment]
As I mentioned in the discord, you'll need to update pydcs (`pip install -r requirements.txt --upgrade`.)   Can you do that and let me know if you still get errors?

**Comment by Khopa** [comment]
I don't have blocking errors after my fix. 
My pydcs version is already the latest from the pydcs repo.

**Comment by Shirooooo** [comment]
Hey wrycu, hey khopa,
Is there a problem with the 1.51 release?

**Comment by wrycu** [comment]
This is my first time, so I had to figure out how to do it. I've cut a test release and sent it to the dev team on our Discord for testing. Once they've gotten back to me with a confirmation that it doesn't crash horribly, I'll add it as a release here.

**Comment by Shirooooo** [comment]
It was a pain to make my first release. Thank you for the update. Good luck with testing.

**Comment by wrycu** [comment]
Made another test release and sent it. If I get the okay from the other devs, I'll make it public.

**Comment by wrycu** [comment]
https://drive.google.com/open?id=1RE4jZyXKEp_vExFY649skCYJYbhjNe7m Please test and let me know if you see any issues. If someone ACKs back with no issues, I'll make it an actual release.

**Comment by Shirooooo** [comment]
Hey @wrycu ,
google is blocking the download, quite likely because there is a bat file in it. Maybe you can upload it on github and mark it as a testrelease?

**Comment by Khopa** [comment]
I have had this issue as well, i'm not able to download this pre-release on Google Drive either.

**Comment by wrycu** [comment]
Created a new release. Please provide feedback on the Discord or via new issues.
